#need super user previlage
sudo: required
services: 
  - docker




before_install: 
  - docker build -t vipin4948/docker-react -f Dockerfile.dev .


#if any return code other than zero in this step travis assumes that build failed
script:
#-e CI=true flag for run test exit from terminal or we can put -- --coverage flag
  - docker run -e CI=true vipin4948/docker-react npm run test


#deploy section for aws

deploy:
#travis ci have default providers
  provider: elasticbeanstack
  region: "ap-south-1"
  #app name given elasticbean stack
  app: "docker-react"
  #env name in aws elastic bean
  env: "Dockerreact-env"
  #elastic bean automatically create buckets
  bucket_name: elasticbeanstalk-ap-south-1-616731952401
  #bucket folder created after first time deployment.so use bucket name
  bucket_path: "docker-react"
  #only attempt to main branch pushes to ncode to travis ci/cd
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
  


