#need super user previlage
sudo: required
services: 
  - docker




before_install: 
  - docker build -t vipin4948/docker-react -f Dockerfile.dev .


#if any return code other than zero in this step travis assumes that build failed
script:
#-e CI=true flag for run test exit from terminal or we can put -- --coverage flag
  - docker run -e CI=true vipin4948/docker-react npm run test
